# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - om_index.md
  - acerca_de.md

footer: 'escuchamos mucho <a href="https://www.youtube.com/watch?v=6_uAAzbv4IE">synthwave</a> mientras creamos este sitio web'

style: dark #light # dark (default) or light
listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag

markdown: kramdown    
remote_theme: b2a3e8/jekyll-theme-console

